/**
 * Constants for Self-Help Ideology Critique - Full Version (English)
 * Comprehensive 5+ minute video with expanded content
 */

// Scene durations in frames (30fps) - matched to actual TTS audio lengths + ~1s buffer
export const SCENE_DURATIONS = {
  INTRO: 480,                    // 16s (audio: 14.2s)
  PARADOX: 780,                  // 26s (audio: 24.6s)
  HAVING_MODE: 750,              // 25s (audio: 23.8s)
  BEING_MODE: 810,               // 27s (audio: 25.3s)
  NEOLIBERALISM: 720,            // 24s (audio: 22.3s)
  ENTREPRENEURIAL_SELF: 690,     // 23s (audio: 21.8s)
  TOXIC_POSITIVITY: 780,         // 26s (audio: 24.6s)
  BELABORED_SELF: 780,           // 26s (audio: 24.1s)
  REAL_WORLD_EXAMPLE: 750,       // 25s (audio: 23.9s)
  SELF_EFFICACY: 660,            // 22s (audio: 20.1s)
  FOUR_SOURCES: 780,             // 26s (audio: 24.2s)
  GROWTH_MINDSET_LIMITS: 720,    // 24s (audio: 22.7s)
  STRUCTURAL_BALANCE: 630,       // 21s (audio: 19.7s)
  OUTRO: 690,                    // 23s (audio: 21.2s)
} as const;

// Calculate scene start times
export const SCENES = {
  INTRO: { start: 0, duration: SCENE_DURATIONS.INTRO },
  PARADOX: {
    start: SCENE_DURATIONS.INTRO,
    duration: SCENE_DURATIONS.PARADOX
  },
  HAVING_MODE: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX,
    duration: SCENE_DURATIONS.HAVING_MODE
  },
  BEING_MODE: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE,
    duration: SCENE_DURATIONS.BEING_MODE
  },
  NEOLIBERALISM: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE,
    duration: SCENE_DURATIONS.NEOLIBERALISM
  },
  ENTREPRENEURIAL_SELF: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM,
    duration: SCENE_DURATIONS.ENTREPRENEURIAL_SELF
  },
  TOXIC_POSITIVITY: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF,
    duration: SCENE_DURATIONS.TOXIC_POSITIVITY
  },
  BELABORED_SELF: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF + SCENE_DURATIONS.TOXIC_POSITIVITY,
    duration: SCENE_DURATIONS.BELABORED_SELF
  },
  REAL_WORLD_EXAMPLE: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF + SCENE_DURATIONS.TOXIC_POSITIVITY + SCENE_DURATIONS.BELABORED_SELF,
    duration: SCENE_DURATIONS.REAL_WORLD_EXAMPLE
  },
  SELF_EFFICACY: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF + SCENE_DURATIONS.TOXIC_POSITIVITY + SCENE_DURATIONS.BELABORED_SELF + SCENE_DURATIONS.REAL_WORLD_EXAMPLE,
    duration: SCENE_DURATIONS.SELF_EFFICACY
  },
  FOUR_SOURCES: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF + SCENE_DURATIONS.TOXIC_POSITIVITY + SCENE_DURATIONS.BELABORED_SELF + SCENE_DURATIONS.REAL_WORLD_EXAMPLE + SCENE_DURATIONS.SELF_EFFICACY,
    duration: SCENE_DURATIONS.FOUR_SOURCES
  },
  GROWTH_MINDSET_LIMITS: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF + SCENE_DURATIONS.TOXIC_POSITIVITY + SCENE_DURATIONS.BELABORED_SELF + SCENE_DURATIONS.REAL_WORLD_EXAMPLE + SCENE_DURATIONS.SELF_EFFICACY + SCENE_DURATIONS.FOUR_SOURCES,
    duration: SCENE_DURATIONS.GROWTH_MINDSET_LIMITS
  },
  STRUCTURAL_BALANCE: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF + SCENE_DURATIONS.TOXIC_POSITIVITY + SCENE_DURATIONS.BELABORED_SELF + SCENE_DURATIONS.REAL_WORLD_EXAMPLE + SCENE_DURATIONS.SELF_EFFICACY + SCENE_DURATIONS.FOUR_SOURCES + SCENE_DURATIONS.GROWTH_MINDSET_LIMITS,
    duration: SCENE_DURATIONS.STRUCTURAL_BALANCE
  },
  OUTRO: {
    start: SCENE_DURATIONS.INTRO + SCENE_DURATIONS.PARADOX + SCENE_DURATIONS.HAVING_MODE + SCENE_DURATIONS.BEING_MODE + SCENE_DURATIONS.NEOLIBERALISM + SCENE_DURATIONS.ENTREPRENEURIAL_SELF + SCENE_DURATIONS.TOXIC_POSITIVITY + SCENE_DURATIONS.BELABORED_SELF + SCENE_DURATIONS.REAL_WORLD_EXAMPLE + SCENE_DURATIONS.SELF_EFFICACY + SCENE_DURATIONS.FOUR_SOURCES + SCENE_DURATIONS.GROWTH_MINDSET_LIMITS + SCENE_DURATIONS.STRUCTURAL_BALANCE,
    duration: SCENE_DURATIONS.OUTRO
  },
} as const;

// Total duration
export const TOTAL_DURATION = Object.values(SCENE_DURATIONS).reduce((a, b) => a + b, 0);
// 10020 frames = 334 seconds = 5:34

export const VIDEO_METADATA = {
  title: "Why Self-Help Books Might Be Making You Worse",
  description: "A comprehensive critical analysis of self-help ideology",
  tags: [
    "self-help",
    "personal development",
    "psychology",
    "philosophy",
    "toxic positivity",
    "neoliberalism",
    "self-efficacy",
    "critical thinking",
  ],
} as const;
